<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cinema.Data\Cinema.Data.csproj" />
    <ProjectReference Include="..\Cinema.Data.Model\Cinema.Data.Model.csproj" />
    <ProjectReference Include="..\Cinema\Cinema.csproj" />
    <ProjectReference Include="..\Cinema.Biz.Model\Cinema.Biz.Model.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
  </ItemGroup>
</Project>
