import { makeStyles } from "@material-ui/core";

const useStyles = makeStyles((theme) => ({
  carousel: {
    position: "relative",
    zIndex: 1,
    backgroundImage:
      'linear-gradient(158deg, rgba(13,19,35,0.85) 0%, rgba(7,14,28,0.92) 52%, rgba(5,9,20,0.95) 100%)',
    backgroundColor: "#050914",
    overflow: "hidden",
  },
  itemSlider: {
    position: "relative",
  },
  img: {
    height: "100%",
    width: "100%",
    objectFit: "cover",
    filter: "brightness(0.7)",
  },
  backgroundLinear: {
    position: "absolute",
    width: "100%",
    height: "100%",
    background: "linear-gradient(110deg, rgba(5,7,18,0.92) 5%, rgba(5,7,18,0.35) 62%, rgba(5,7,18,0.85) 100%)",
    top: 0,
    left: 0,
    cursor: "pointer",
  },
  heroOverlay: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    padding: theme.spacing(0, 6),
    pointerEvents: "none",
    [theme.breakpoints.down("sm")]: {
      padding: theme.spacing(0, 3, 8),
      alignItems: "flex-end",
    },
  },
  heroInner: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.2fr) minmax(0, 0.8fr)",
    alignItems: "center",
    gap: theme.spacing(6),
    width: "100%",
    pointerEvents: "none",
    [theme.breakpoints.down("md")]: {
      gridTemplateColumns: "minmax(0, 1fr)",
    },
  },
  heroContent: {
    maxWidth: 560,
    color: "#f5f7ff",
    pointerEvents: "auto",
  },
  heroEyebrow: {
    display: "inline-flex",
    alignItems: "center",
    gap: theme.spacing(1),
    padding: theme.spacing(0.5, 2.5),
    borderRadius: 999,
    background: "rgba(148, 163, 184, 0.18)",
    color: "#f8fafc",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontSize: "0.75rem",
    marginBottom: theme.spacing(2),
  },
  heroTitle: {
    fontSize: "3rem",
    lineHeight: 1.15,
    fontWeight: 700,
    color: "#ffcf9f",
    margin: 0,
    marginBottom: theme.spacing(2),
    [theme.breakpoints.down("sm")]: {
      fontSize: "2.2rem",
    },
  },
  heroSubtitle: {
    fontSize: "1.05rem",
    lineHeight: 1.7,
    color: "rgba(245, 247, 255, 0.82)",
    marginBottom: theme.spacing(4),
  },
  heroActions: {
    display: "flex",
    gap: theme.spacing(2),
    flexWrap: "wrap",
  },
  heroPrimaryButton: {
    background: "linear-gradient(135deg, #f97316 0%, #fb7185 100%)",
    color: "#fff",
    padding: theme.spacing(1.5, 4),
    borderRadius: 999,
    fontWeight: 600,
    textTransform: "none",
    boxShadow: "0 18px 35px rgba(251, 113, 133, 0.4)",
    '&:hover': {
      background: "linear-gradient(135deg, #fb923c 0%, #f43f5e 100%)",
    },
  },
  heroSecondaryButton: {
    borderRadius: 999,
    padding: theme.spacing(1.5, 3.5),
    border: "1px solid rgba(248, 250, 252, 0.5)",
    color: "#f5f7ff",
    textTransform: "none",
    fontWeight: 600,
    background: "rgba(255, 255, 255, 0.05)",
    '&:hover': {
      background: "rgba(255, 255, 255, 0.12)",
    },
  },
  heroAside: {
    pointerEvents: "auto",
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
  highlightCard: {
    borderRadius: theme.spacing(3),
    background: "rgba(15, 23, 42, 0.82)",
    border: "1px solid rgba(148, 163, 184, 0.18)",
    boxShadow: "0 30px 60px -35px rgba(15, 23, 42, 0.85)",
    overflow: "hidden",
    width: 320,
    display: "flex",
    flexDirection: "column",
  },
  highlightPosterWrap: {
    position: "relative",
    overflow: "hidden",
  },
  highlightPoster: {
    width: "100%",
    height: 190,
    objectFit: "cover",
    display: "block",
  },
  highlightBadge: {
    position: "absolute",
    bottom: theme.spacing(1.5),
    right: theme.spacing(1.5),
    padding: theme.spacing(0.5, 1.5),
    borderRadius: 999,
    background: "linear-gradient(135deg, rgba(56,189,248,0.95), rgba(14,165,233,0.85))",
    color: "#0f172a",
    fontWeight: 600,
    fontSize: "0.75rem",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  highlightBody: {
    padding: theme.spacing(3),
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(1.25),
  },
  highlightTitle: {
    color: "#f8fafc",
    margin: 0,
    fontSize: "1.2rem",
    fontWeight: 600,
  },
  highlightMeta: {
    margin: 0,
    color: "rgba(226, 232, 240, 0.7)",
    fontSize: "0.95rem",
  },
  highlightButton: {
    alignSelf: "flex-start",
    marginTop: theme.spacing(1),
    borderRadius: 999,
    padding: theme.spacing(0.75, 2.5),
    background: "rgba(59, 130, 246, 0.18)",
    color: "#38bdf8",
    textTransform: "none",
    fontWeight: 600,
    '&:hover': {
      background: "rgba(59, 130, 246, 0.3)",
    },
  },
  Arrow: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 2,
    width: 48,
    height: 96,
    color: "rgba(255, 255, 255, 0.65) !important",
    cursor: "pointer",
    transition: "all .2s",
    '&:hover': { color: "#f97316 !important" },
    [theme.breakpoints.down("md")]: {
      display: "none",
    },
  },
}));

export default useStyles;